# Configuración para Integración del Servicio Externo de Productos
external.service.producto.url=https://documenter.getpostman.com/view/19876210/Uz5MFtdn#5eb05db8-9056-4006-ae99-37a9bafde394
external.service.producto.token=AMBG_SRR
external.service.producto.connect-timeout=5000
external.service.producto.read-timeout=5000